hollymovies_7/urls.py
from django.contrib import admin
from django.urls import path, include
from movies.views import HomepageView, ActorListView, MovieListView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movies.urls'))
]

movies/urls.py
from django.urls import path
from movies.views import HomepageView, ActorListView, MovieListView, MovieDetailView, \
    ActorDetailView, Jinja2TestingView, DirectorListView, DirectorDetailView, ContactView, CreateMovieView, \
    CreateActorView, CreateDirectorView, UpdateMovieView, UpdateActorView, UpdateDirectorView, DeleteMovieView, \
    DeleteActorView, DeleteDirectorView

urlpatterns = [
    path('', HomepageView.as_view(), name='homepage'),
    path('actors/', ActorListView.as_view(), name='actors'),
    path('movies/', MovieListView.as_view(), name='movies'),
    path('directors/', DirectorListView.as_view(), name='directors'),
    path('movie/<int:pk>/', MovieDetailView.as_view(), name='movie_detail'),
    path('actor/<int:pk>/', ActorDetailView.as_view(), name='actor_detail'),
    path('director/<int:pk>/', DirectorDetailView.as_view(), name='director_detail'),
    path('testing/', Jinja2TestingView.as_view(), name='jinja2_testing_view'),
    path('contact/', ContactView.as_view(), name='contact_view'),
    path('movie/create/', CreateMovieView.as_view(), name='create_movie'),
    path('actor/create/', CreateActorView.as_view(), name='create_actor'),
    path('director/create/', CreateDirectorView.as_view(), name='create_director'),
    path('movie/update/<int:pk>/', UpdateMovieView.as_view(), name='update_movie'),
    path('actor/update/<int:pk>/', UpdateActorView.as_view(), name='update_actor'),
    path('director/update/<int:pk>/', UpdateDirectorView.as_view(), name='update_director'),
    path('movie/delete/<int:pk>/', DeleteMovieView.as_view(), name='delete_movie'),
    path('actor/delete/<int:pk>/', DeleteActorView.as_view(), name='delete_actor'),
    path('director/delete/<int:pk>/', DeleteDirectorView.as_view(), name='delete_director'),
]

movies/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.shortcuts import resolve_url


class BasePersonModel(models.Model):
    GENDER_MALE = 'male'
    GENDER_FEMALE = 'female'

    GENDER_CHOICES = (
        (GENDER_MALE, 'male'),
        (GENDER_FEMALE, 'female')
    )

    name = models.CharField(max_length=256)
    age = models.IntegerField()
    gender = models.CharField(choices=GENDER_CHOICES, max_length=100)
    born_at = models.DateField()
    # movies = models.ManyToManyField('Movie', related_name='actors')


    def __str__(self):
        return self.name

    class Meta:
        abstract = True


class Actor(BasePersonModel):
    def get_absolute_url(self):
        return resolve_url('actor_detail', pk=self.id)


class Director(BasePersonModel):
    def get_absolute_url(self):
        return resolve_url('director_detail', pk=self.id)


    # GENDER_MALE = 'male'
    # GENDER_FEMALE = 'female'
    #
    # GENDER_CHOICES = (
    #     (GENDER_MALE, 'male'),
    #     (GENDER_FEMALE, 'female')
    # )
    #
    # name = models.CharField(max_length=256)
    # age = models.IntegerField()
    # gender = models.CharField(choices=GENDER_CHOICES, max_length=100)
    # born_at = models.DateField()
    #
    # def __str__(self):
    #     return self.name


class Movie(models.Model):
    LANGUAGE_ENG = 'eng'
    LANGUAGE_CZ = 'cz'

    LANGUAGE_CHOICES = (
        (LANGUAGE_ENG, 'english'),
        (LANGUAGE_CZ, 'czech'),
    )

    name = models.CharField(max_length=256)
    description = models.TextField()
    rating = models.IntegerField(validators=[
        MinValueValidator(0), MaxValueValidator(100)
    ])
    language = models.CharField(choices=LANGUAGE_CHOICES, max_length=5)
    released = models.DateField()
    actors = models.ManyToManyField('Actor', related_name='movies')
    director = models.ForeignKey(
        'Director',
        on_delete=models.SET_NULL,
        related_name='movies',
        null=True, blank=True
    )
    likes = models.IntegerField(default=0)

    # # mohu zmenit jmeno tridy 'Movies' na 'Filmy'
    # class Meta:
    #     verbose_name_plural = 'Filmy'

    def __str__(self):
        return f'{self.name} : {self.id}'

    def get_absolute_url(self):
        return resolve_url('movie_detail', pk=self.id)


class Contact(models.Model):
    name = models.CharField(max_length=37)
    email = models.EmailField()
    subject = models.TextField()
    phone_number = models.IntegerField()
    contact_at = models.DateField()

movies/forms.py
from datetime import timedelta

from django import forms
from django.core.exceptions import ValidationError
from django.utils import timezone
from movies.models import Movie, Actor, Director


class DatePickerDateInput(forms.DateInput):
    def __init__(self, *args, **kwargs):
        kwargs.update({'attrs': {'type': 'date'}})
        super(DatePickerDateInput, self).__init__(*args, **kwargs)


class DateFieldSevenDaysFromNow(forms.DateField):
    widget = DatePickerDateInput

    def validate(self, value):
        super(DateFieldSevenDaysFromNow, self).validate(value)
        if value < timezone.now().date() + timedelta(days=7):
            raise ValidationError('Cannot create contact at earlier than 7 days from now')


def contact_name_is_not_david(value):
    if 'david' in value.lower():
        raise ValidationError('David cannot create contact')


class ContactForm(forms.Form):
    name = forms.CharField(validators=[contact_name_is_not_david, ])
    email = forms.EmailField()
    subject = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}))
    phone_number = forms.IntegerField()
    age = forms.IntegerField(min_value=1, max_value=99)
    contact_at = DateFieldSevenDaysFromNow()
    subscribe = forms.BooleanField()

    # funkce clean_name umoznuje upravovat data zadavajiciho, napr. upravit jmena kontaktu na mala pismena
    def clean_name(self):
        return self.data.get('name').lower()


class MovieForm(forms.ModelForm):
    released = forms.DateField(widget=DatePickerDateInput())

    class Meta:
        model = Movie
        fields = '__all__'
        exclude = ['likes', ]

    def save(self, commit=True):
        movie = super(MovieForm, self).save(commit=commit)
        movie.movies.add(*self.cleaned_data.get('movies'))
        return movie


class ActorForm(forms.ModelForm):
    born_at = forms.DateField(widget=DatePickerDateInput())
    movies = forms.ModelMultipleChoiceField(queryset=Movie.objects.all(), required=False)

    class Meta:
        model = Actor
        fields = '__all__'

    def save(self, commit=True):
        actor = super(ActorForm, self).save(commit=commit)
        actor.movies.add(*self.cleaned_data.get('movies'))
        return actor


class DirectorForm(forms.ModelForm):
    born_at = forms.DateField(widget=DatePickerDateInput())
    movies = forms.ModelMultipleChoiceField(queryset=Movie.objects.all(), required=False)

    class Meta:
        model = Director
        fields = '__all__'

    def save(self, commit=True):
        director = super(DirectorForm, self).save(commit=commit)
        director.movies.add(*self.cleaned_data.get('movies'))
        return director

movies/views.py
from django.http import HttpResponse
from django.shortcuts import redirect
from django.template.response import TemplateResponse
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, TemplateView, FormView, CreateView, UpdateView, DeleteView
from movies.forms import ContactForm, MovieForm, ActorForm, DirectorForm

from movies.models import Movie, Actor, Director, Contact
from django.views import View


class HomepageView(View):
    def get(self, request, *args, **kwargs):
        context = {
            'number_of_movies': Movie.objects.all().count(),
            'number_of_actors': Actor.objects.all().count(),
            'number_of_directors': Director.objects.all().count(),
            'page_name': 'homepage'
        }
        return TemplateResponse(request, 'homepage.html', context=context)


# def homepage_view(request):
# if request.method == 'GET':
#     context = {
#         'number_of_movies': Movie.objects.all().count(),
#         'number_of_actors': Actor.objects.all().count(),
#         'page_name': 'homepage'
#     }
#     return TemplateResponse(request, 'homepage.html', context=context)
# elif request.method == 'POST':
#     return HttpResponse(request, 'method not allowed')


class ActorListView(ListView):
    model = Actor
    template_name = 'actors.html'
    extra_context = {'page_name': 'Actors'}


class HollymoviesDetailView(DetailView):
    def get_context_data(self, **kwargs):
        context = super(HollymoviesDetailView, self).get_context_data(**kwargs)
        context.update({'page_name': self.object.name})
        return context


class ActorDetailView(HollymoviesDetailView):
    model = Actor
    template_name = 'actor_detail.html'


# def actors_view(request):
#     actors = Actor.objects.all()
#     context = {
#         'all_actors': actors,
#         'page_name': 'Actors'
#     }
#     return TemplateResponse(request, 'actors.html', context=context)


class DirectorListView(ListView):
    model = Director
    template_name = 'directors.html'
    extra_context = {'page_name': 'Directors'}


class DirectorDetailView(HollymoviesDetailView):
    model = Director
    template_name = 'actor_detail.html'


class MovieListView(ListView):
    queryset = Movie.objects.all().order_by('-rating')
    template_name = 'movies.html'

    def get_context_data(self, *args, **kwargs):
        context = super(MovieListView, self).get_context_data(*args, **kwargs)
        context.update({
            'page_name': 'Movies',
            'best_movies': Movie.objects.filter(rating__gte=80).order_by('-rating'),
            'worst_movies': Movie.objects.filter(rating__lte=20).order_by('rating')
        })
        return context


class MovieDetailView(HollymoviesDetailView):
    model = Movie
    template_name = 'movie_detail.html'

    def post(self, request, pk, *args, **kwargs):
        movie = self.get_object()
        movie.likes += 1
        movie.save(update_fields=['likes', ])
        return redirect('movie_detail', pk=pk)


 # def get_context_data(self, **kwargs):
#     context = super(MovieDetailView, self).get_context_data(**kwargs)
#     context.update({'page_name': self.object.name})
#     return context


# def movies_view(request):
#     all_movies = Movie.objects.all().order_by('-rating')   # SELECT * FROM movies_movie;
#     best_movies = Movie.objects.filter(rating__gte=80).order_by('-rating')  # SELECT * FROM movies_movie WHERE rating GTE 80;
#     worst_movies = Movie.objects.filter(rating__lte=20).order_by('rating')
#     context = {
#         'all_movies': all_movies,
#         'best_movies': best_movies,
#         'worst_movies': worst_movies,
#         'page_name': 'Movies'
#     }
#     return TemplateResponse(request, 'movies.html', context=context)


class Jinja2TestingView(TemplateView):
    template_name = 'jinja2_testing.html'
    extra_context = {
        'testing_list': ['index_1', 'index_2', 'index_3'],
        'testing_dict': {'key_1': 'value_1', 'key_2': 'value_2'},
        'testing_queryset': Movie.objects.all(),
        'page_name': 'Testing'
    }


# def jinja2_testing_view(request):
#     index_list = ['index_1', 'index_2', 'index_3']
#     index_1 = index_list[0]
#
#     testing_dict = {'key_1': 'value_1', 'key_2': 'value_2'}
#     value_1 = testing_dict['key_1']
#
#     context = {
#         'testing_list': index_list,
#         'testing_dict': testing_dict,
#         'testing_queryset': Movie.objects.all(),
#         'page_name': 'Testing'
#     }
#     return TemplateResponse(request, 'jinja2_testing.html', context=context)


# class ContactView(View):
#     def get(self, request, *args, **kwargs):
#         context = {
#             'contact_form': ContactForm(),
#             'page_name': 'Contact'
#         }
#         return TemplateResponse(request, 'contact.html', context=context)
#
#     def post(self, request, *args, **kwargs):
#         bounded_form = ContactForm(request.POST)
#         if not bounded_form.is_valid():
#             return TemplateResponse(request, 'contact.html', context={'contact_form': ContactForm()})
#
#         name = bounded_form.cleaned_data.get('name')
#         phone_number = bounded_form.cleaned_data.get('phone_number')
#         email = bounded_form.cleaned_data.get('email')
#         subject = bounded_form.cleaned_data.get('subject')
#         contact_at = bounded_form.cleaned_data.get('contact_at')
#
#         Contact.objects.create(
#             name=name,
#             phone_number=phone_number,
#             email=email,
#             subject=subject,
#             contact_at=contact_at
#         )
#
#         return TemplateResponse(request, 'contact.html', context={'contact_form': ContactForm()})

class ContactView(FormView):
    template_name = 'contact.html'
    form_class = ContactForm
    extra_context = {'page_name': 'Contact'}

    def form_valid(self, form):
        name = form.cleaned_data.get('name')
        phone_number = form.cleaned_data.get('phone_number')
        email = form.cleaned_data.get('email')
        subject = form.cleaned_data.get('subject')
        contact_at = form.cleaned_data.get('contact_at')

        Contact.objects.create(
            name=name,
            phone_number=phone_number,
            email=email,
            subject=subject,
            contact_at=contact_at
        )
        return TemplateResponse(self.request, 'contact.html', context={'form': ContactForm()})

    def form_invalid(self, form):
        return TemplateResponse(self.request, 'contact.html', context={'form': form})


class CreateMovieView(CreateView):
    template_name = 'movie_create.html'
    form_class = MovieForm
    model = Movie
    extra_context = {'page_name': 'Create movie'}


class CreateActorView(CreateView):
    template_name = 'actor_create.html'
    form_class = ActorForm
    model = Actor
    extra_context = {'page_name': 'Create actor'}


class CreateDirectorView(CreateView):
    template_name = 'director_create.html'
    form_class = DirectorForm
    model = Director
    extra_context = {'page_name': 'Create director'}


class UpdateMovieView(UpdateView):
    template_name = 'movie_update.html'
    form_class = MovieForm
    model = Movie
    extra_context = {'page_name': 'Update movie'}


class UpdateActorView(UpdateView):
    template_name = 'actor_update.html'
    form_class = ActorForm
    model = Actor
    extra_context = {'page_name': 'Update actor'}


class UpdateDirectorView(UpdateView):
    template_name = 'director_update.html'
    form_class = DirectorForm
    model = Director
    extra_context = {'page_name': 'Update director'}


class DeleteMovieView(DeleteView):
    template_name = 'movie_confirm_delete.html'
    model = Movie
    success_url = reverse_lazy('movies')
    extra_context = {'page_name': 'Delete movie'}


class DeleteActorView(DeleteView):
    template_name = 'actor_confirm_delete.html'
    model = Actor
    success_url = reverse_lazy('actors')
    extra_context = {'page_name': 'Delete actor'}


class DeleteDirectorView(DeleteView):
    template_name = 'director_confirm_delete.html'
    model = Director
    success_url = reverse_lazy('directors')
    extra_context = {'page_name': 'Delete director'}

movies/templates/actor_confirm_delete.html
{% extends "base.html" %}

{% block body %}
  <form method="post">
    {% csrf_token %}
    <p>
      Are you sure you want to delete actor <b>"{{ object.name }}"</b> from database?
    </p>
    <input type="submit" value="Delete">
  </form>
{% endblock %}

movies/templates/actor_detail.html
{% include 'base.html' %}


{% block body %}
  Name: {{ object.name }}<br>
  Age: {{ object.age }}<br>
  Gender: {{ object.get_gender_display }}<br>
  Born at : {{ object.born_at|date:'d.m Y' }}<br><br><br>
  Movies:<br><br>
  {% for movie in object.movies.all %}
    {{ movie.name }}<br>
  {% endfor %}
{% endblock body %}

movies/templates/actor_update.html
{% extends 'base.html' %}

{% block body %}
    <form action="{% url 'update_actor' object.id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}<br>
        <input type="submit" value="Update actor">
    </form>
  <br><br>
    <a href="{% url 'delete_actor' object.id %}">Delete</a>
{% endblock body %}

movies/templates/actors.html
{% include 'base.html' %}

{% block body %}
  {% for actor in object_list %}
    <p>{{ actor.name }} age: {{ actor.age }} - <a href="{% url 'actor_detail' actor.id %}">detail</a> - <a href="{% url 'update_actor' actor.id %}">update</a></p>
  {% endfor %}
{% endblock body %}

movies/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
</head>
<body style="background: #e8ceb7">
<h1>Vítám Vás v aplikaci Hollymovies - {{ page_name }}</h1><br>

{% block navbar %}
  <a href="{% url 'homepage' %}">Homepage</a><br><br>
  <a href="{% url 'actors' %}">Actors</a><br>
  <a href="{% url 'movies' %}">Movies</a><br>
  <a href="{% url 'directors' %}">Directors</a><br><br>
  <a href="{% url 'create_movie' %}">Create Movie</a><br>
  <a href="{% url 'create_actor' %}">Create Actor</a><br>
  <a href="{% url 'create_director' %}">Create Director</a><br><br>
  <a href="{% url 'jinja2_testing_view' %}">Template cheatsheet</a><br>
  <a href="{% url 'contact_view' %}">Contact</a><br><br>
{% endblock navbar %}

{% block body %}
{% endblock body %}

</body>
</html>

movies/templates/contact.html
{% extends 'base.html' %}

{% block body %}
  <form action="{% url 'contact_view' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="submit">
  </form>
{% endblock body %}

movies/templates/director_confirm_delete.html
{% extends "base.html" %}

{% block body %}
  <form method="post">
    {% csrf_token %}
    <p>
      Are you sure you want to delete director <b>"{{ object.name }}"</b> from database?
    </p>
    <input type="submit" value="Delete">
  </form>
{% endblock %}

movies/templates/director_create.html
{% extends 'base.html' %}

{% block body %}
  <form action="{% url 'create_director' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Create director">
  </form>
{% endblock body %}

movies/templates/director_detail.html
{% include 'base.html' %}


{% block body %}
  Name: {{ object.name }}<br>
  Age: {{ object.age }}<br>
  Gender: {{ object.get_gender_display }}<br>
  Born at : {{ object.born_at|date:'d.m Y' }}<br><br>
  Movies:<br><br>
  {% for movie in object.movies.all %}
    {{ movie.name }}<br>
  {% endfor %}
{% endblock body %}

movies/templates/directors.html
{% include 'base.html' %}

{% block body %}
  {% for director in object_list %}
    <p>{{ director.name }} age: {{ director.age }} - <a href="{% url 'director_detail' director.id %}">detail</a> - <a href="{% url 'update_director' director.id %}">update</a></p>
  {% endfor %}
{% endblock body %}

movies/templates/homepage.html
{% include 'base.html' %}

{% block body %}
  <p>Number of movies - {{ number_of_movies }}</p>
  <p>Number of actors - {{ number_of_actors }}</p>
  <p>Number of directors - {{ number_of_directors }}</p>
{% endblock body %}

movies/templates/jinja2_testing.html
{% extends 'base.html' %}

{% block navbar %}
  <a href="{% url 'homepage' %}">Homepage</a><br><br>
  <a href="https://www.google.com">Google</a><br>
{% endblock navbar %}

{% block body %}
  {{ testing_list.0 }} : {{ testing_list.1 }} : {{ testing_list.2 }}
  <br>
  {{ testing_dict.key_1 }}
  <br>
  {{ testing_queruset.2 }}
{% endblock body %}

movies/templates/movie_detail.html
{% include 'base.html' %}

{% block body %}
  Name: {{ object.name }}<br><br>
  Description: {{ object.description }}<br><br>
  Rating: {{ object.rating }}<br>
  Language: {{ object.get_language_display }}<br>
  Released: {{ object.released|date:'d.m Y'}}<br>
  Likes: {{ object.likes }}<br><br>
  Actors:<br><br>
    {% for actor in object.actors.all %}
      {{ actor.name }}<br>
    {% endfor %}<br>
  Directors:<br>
    {% for director in object.directors.all %}
      {{ director.name }}<br>
    {% endfor %}

  <br><br>
  <form action="{% url 'movie_detail' object.id %}" method="post">
    {% csrf_token %}
    <input type="submit" value="Like">
  </form>

{% endblock body %}

movies/templates/movie_update.html
{% extends 'base.html' %}

{% block body %}
    <form action="{% url 'update_movie' object.id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}<br>
        <input type="submit" value="Update movie">
    </form>
    <br><br>
    <a href="{% url 'delete_movie' object.id %}">Delete</a>
{% endblock body %}